import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Wizard World</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={` ${styles.center}`}>
          <h3 className="text-[32px] sm:text-[72px] mb-8">Wizard World</h3>
          <div className="flex items-center gap-12 z-10">
            <Link href={`/elixirs`}>
              <span className="text-base sm:text-[24px] cursor-pointer hover:underline hover:text-blue-600">
                Elixirs
              </span>
            </Link>
            <Link href={`/spells`}>
              <span className="text-base sm:text-[24px] cursor-pointer hover:underline hover:text-blue-600">
                Spells
              </span>
            </Link>
            <Link href={`/wizards`}>
              <span className="text-base sm:text-[24px] cursor-pointer hover:underline hover:text-blue-600">
                Wizards
              </span>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
